DICCIONARIO DE DATOS: COFFE QUALITY DATASET

1. Identidad y Trazabilidad

 - Unnamed: 0: Índice numérico residual del archivo original; no tiene valor analítico.
 
 - Species: Tipo de especie botánica (Arabica o Robusta).
 
 - Owner / Owner.1: Persona o entidad dueña del lote de café.

 - Country.of.Origin: País de procedencia del grano.

 - Farm.Name: Nombre de la finca productora.

 - Lot.Number: Código de identificación del lote específico.

 - Mill: Nombre del beneficio o planta donde se procesó el café.

 - ICO.Number: Registro internacional ante la International Coffee Organization.

 - Company: Empresa exportadora o comercializadora.

 - Region: Zona geográfica específica dentro del país de origen.

 - Producer: Nombre del productor o caficultor.

 - In.Country.Partner: Organización que coordina la certificación en el país origen (ej. Almacafé).

2. Logística y Certificación

 - Number.of.Bags: Cantidad total de sacos en el lote.

 - Bag.Weight: Peso de cada saco individual.

 - Harvest.Year: Periodo o año de la cosecha.

 - Grading.Date: Fecha en la que se realizó la evaluación técnica.

 - Expiration: Fecha límite de validez de la certificación.

 - Certification.Body: Entidad encargada de emitir el certificado de calidad.

 - Certification.Address / Contact: Datos de ubicación y contacto de la certificadora.

3. Atributos Sensoriales

 - Aroma: Fragancia del café en seco y su olor al contacto con agua caliente.

 - Flavor: Intensidad y calidad del sabor percibido.

 - Aftertaste: Calidad del sabor remanente tras la degustación.

 - Acidity: Nivel de brillantez y viveza del grano.

 - Body: Textura y sensación de peso en el paladar.

 - Balance: Equilibrio entre aroma, sabor, acidez y cuerpo.

 - Uniformity: Consistencia de sabor entre las distintas tazas de la muestra.

 - Clean.Cup: Ausencia de sabores defectuosos o "sucios".

 - Sweetness: Presencia de dulzor natural en el grano.

 - Cupper.Points: Calificación global otorgada por el catador.

 - Total.Cup.Points: Variable objetivo (Target). Puntaje final sobre 100 puntos.

4. Atributos Físicos y Defectos

 - Moisture: Grado de humedad del grano verde.

 - Color: Tono visual del café (Verde, Azulado, etc.).

 - Category.One.Defects: Conteo de defectos primarios (los más graves).

 - Category.Two.Defects: Conteo de defectos secundarios (leves).

 - Quakers: Granos que no se tuestan bien por falta de madurez.

5. Altitud

 - Altitude: Texto original con la información de altura (sin procesar).

 - unit_of_measurement: Unidad utilizada en el registro original (ft o m).

 - altitude_low_meters: Valor mínimo del rango de altitud en metros.

 - altitude_high_meters: Valor máximo del rango de altitud en metros.

 - altitude_mean_meters: Promedio de altitud calculado y normalizado

# 1. Importación de Librerías

In [1]:
import pandas as pd
import numpy as np

# 2. Cargar el Dataset

In [2]:
df_merged = pd.read_csv("../data/raw/merged_data_cleaned.csv")

# 3. Vista Inicial del Dataset

In [4]:
df_merged.head(3)

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0

# 4. Análisis de valores faltantes (nulos)

In [5]:
print(df_merged.isnull().sum().sort_values(ascending=False).head(50))

Lot.Number               1063
Farm.Name                 359
Mill                      318
Color                     270
Producer                  232
altitude_mean_meters      230
altitude_high_meters      230
altitude_low_meters       230
Altitude                  226
Variety                   226
Company                   209
Processing.Method         170
ICO.Number                159
Region                     59
Harvest.Year               47
Owner                       7
Owner.1                     7
Quakers                     1
Country.of.Origin           1
Unnamed: 0                  0
Species                     0
Aroma                       0
Aftertaste                  0
Flavor                      0
In.Country.Partner          0
Bag.Weight                  0
Number.of.Bags              0
Grading.Date                0
Clean.Cup                   0
Uniformity                  0
Balance                     0
Body                        0
Acidity                     0
Moisture                    0
Sweetness                   0
Cupper.Points               0
Category.Two.Defects        0
Category.One.Defects        0
Total.Cup.Points            0
Expiration                  0
Certification.Contact       0
Certification.Address       0
Certification.Body          0
unit_of_measurement         0
dtype: int64

# 5. Limpieza y relleno de valores faltantes

In [6]:
#Las columnas que eliminamos no aportan valor o tienen demasiados nulos son las siguientes:

cols_to_drop = [
    'Lot.Number', 'Farm.Name', 'Mill', 'Producer', 'Company', 
    'ICO.Number', 'Owner.1',
    'Quakers', 'Expiration', 'Certification.Body', 'Unnamed: 0',    
    'Harvest.Year', 
    #Aclaración: Si bien 'Harvest.Year' podría ser interesante, tiene demasiados nulos, 
    #por lo que decidimos utilizar Grading.Date como fecha de referencia aproximada de cosecha.
    'Certification.Address', 'Certification.Contact', 'Altitude']
df_merged_limpio = df_merged.drop(columns=cols_to_drop, errors='ignore')

En cuanto a la columna 'Owner', decidimos rellenar los valores nulos con 'Desconocido' para mantener la información de que no se conoce el propietario, en lugar de eliminar la columna o dejarla con valores nulos.

In [7]:
df_merged_limpio['Owner'] = df_merged_limpio['Owner'].fillna('Desconocido')

Para la columna 'Country.of.Origin', decidimos rellenar el unico valor nulo con 'United States' ya que identificamos que el café con ese In.Country.Partner provenía de ese país.

In [8]:
df_merged_limpio.loc[df_merged_limpio['Country.of.Origin'].isnull(), 'Country.of.Origin'] = 'United States'

Ahora, para las columnas categóricas restantes, vamos a rellenar los valores nulos con la moda de cada grupo definido por 'Country.of.Origin' y 'Species'.

In [9]:
cols_moda = ['Color', 'Variety', 'Processing.Method']

for col in cols_moda:
    moda_por_grupo = df_merged_limpio.groupby(['Country.of.Origin', 'Species'])[col].transform(
        lambda x: x.mode()[0] if not x.mode().empty else "No Especificado"
    )
    df_merged_limpio[col] = df_merged_limpio[col].fillna(moda_por_grupo)

# Para la Región, simplemente rellenamos con "No Especificado" sin buscar la moda
df_merged_limpio['Region'] = df_merged_limpio['Region'].fillna("No Especificado")

# Verificación de seguridad
print("Nulos por columna:")
print(df_merged_limpio[cols_moda + ['Region']].isnull().sum())

Nulos por columna:
Color                0
Variety              0
Processing.Method    0
Region               0
dtype: int64

In [10]:
df_merged_limpio.head(3)

,Species,Owner,Country.of.Origin,Region,Number.of.Bags,Bag.Weight,In.Country.Partner,Grading.Date,Variety,Processing.Method,...,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Color,Category.Two.Defects,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,Arabica,metad plc,Ethiopia,guji-hambela,300,60 kg,METAD Agricultural Development plc,"April 4th, 2015",Other,Washed / Wet,...,8.75,90.58,0.12,0,Green,0,m,1950.0,2200.0,2075.0
1,Arabica,metad plc,Ethiopia,guji-hambela,300,60 kg,METAD Agricultural Development plc,"April 4th, 2015",Other,Washed / Wet,...,8.58,89.92,0.12,0,Green,1,m,1950.0,2200.0,2075.0
2,Arabica,grounds for health admin,Guatemala,No Especificado,5,1,Specialty Coffee Association,"May 31st, 2010",Bourbon,Washed / Wet,...,9.25,89.75,0.00,0,Green,0,m,1600.0,1800.0,1700.0

Análisis de valores faltantes

In [11]:
print(df_merged_limpio.isnull().sum().sort_values(ascending=False).head(50))

altitude_mean_meters    230
altitude_low_meters     230
altitude_high_meters    230
Owner                     0
Species                   0
Bag.Weight                0
In.Country.Partner        0
Grading.Date              0
Variety                   0
Processing.Method         0
Country.of.Origin         0
Region                    0
Number.of.Bags            0
Aftertaste                0
Flavor                    0
Aroma                     0
Acidity                   0
Clean.Cup                 0
Body                      0
Balance                   0
Uniformity                0
Total.Cup.Points          0
Cupper.Points             0
Sweetness                 0
Moisture                  0
Category.Two.Defects      0
Color                     0
Category.One.Defects      0
unit_of_measurement       0
dtype: int64

# 6. Limpiar y estandarizar las unidades de altitud

Finalmente, estandarizamos las unidades de altitud a metros, asumiendo que si la unidad es pies, se debe convertir a metros.

In [12]:
def estandarizar_unidades(row):
    unidad = str(row['unit_of_measurement']).lower().strip()
    
    if 'ft' in unidad or 'feet' in unidad:
        cols = ['altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters']
        for col in cols:
            if pd.notnull(row[col]):
                row[col] = row[col] * 0.3048
    return row
df_merged_limpio = df_merged_limpio.apply(estandarizar_unidades, axis=1)

Eliminamos las columnas de altitud Low y High porque ya tenemos la columna de altitud media, que es la que utilizaremos para el análisis, y así simplificamos el DataFrame.

In [13]:
df_merged_limpio= df_merged_limpio.drop(columns=['altitude_low_meters', 'altitude_high_meters', 'unit_of_measurement'], errors='ignore')
print(df_merged_limpio.isnull().sum().sort_values(ascending=False).head(50))

altitude_mean_meters    230
Species                   0
Country.of.Origin         0
Region                    0
Number.of.Bags            0
Bag.Weight                0
In.Country.Partner        0
Grading.Date              0
Variety                   0
Owner                     0
Processing.Method         0
Aroma                     0
Aftertaste                0
Flavor                    0
Body                      0
Balance                   0
Uniformity                0
Acidity                   0
Clean.Cup                 0
Sweetness                 0
Total.Cup.Points          0
Cupper.Points             0
Moisture                  0
Category.One.Defects      0
Color                     0
Category.Two.Defects      0
dtype: int64

Finalmente rellenamos los valores nulos de la columna 'altitude_mean_meters' utilizando la mediana de altitud para cada combinación de 'Country.of.Origin' y 'Species'.

In [14]:
# Paso A: Rellenar usando la mediana del País Y la Especie
df_merged_limpio['altitude_mean_meters'] = df_merged_limpio['altitude_mean_meters'].fillna(
    df_merged_limpio.groupby(['Country.of.Origin', 'Species'])['altitude_mean_meters'].transform('median')
)
# Paso B: Si aún quedan nulos (países con un solo registro nulo), usar la mediana de la Especie
df_merged_limpio['altitude_mean_meters'] = df_merged_limpio['altitude_mean_meters'].fillna(
    df_merged_limpio.groupby('Species')['altitude_mean_meters'].transform('median')
)
print(f"Nulos restantes en altitud: {df_merged_limpio['altitude_mean_meters'].isnull().sum()}")

Nulos restantes en altitud: 0

Agregamos una nueva columna que categorice la altitud en rangos, diferenciando entre Arabica y Robusta, para facilitar el análisis posterior.

In [15]:
def categorizar_altitud_pro(row):
    metros = row['altitude_mean_meters']
    especie = row['Species']
    
    if especie == 'Arabica':
        if metros < 1000: return 'Baja (Arabica)'
        if 1000 <= metros < 1500: return 'Media (Arabica)'
        if 1500 <= metros < 1800: return 'Alta (Arabica)'
        return 'Premium (Arabica)'
    
    else:
        if metros < 400: return 'Baja (Robusta)'
        if 400 <= metros < 700: return 'Media (Robusta)'
        return 'Alta (Robusta)'

df_merged_limpio['categoria_altitud'] = df_merged_limpio.apply(categorizar_altitud_pro, axis=1)

In [16]:
df_merged_limpio

,Species,Owner,Country.of.Origin,Region,Number.of.Bags,Bag.Weight,In.Country.Partner,Grading.Date,Variety,Processing.Method,...,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Color,Category.Two.Defects,altitude_mean_meters,categoria_altitud
0,Arabica,metad plc,Ethiopia,guji-hambela,300,60 kg,METAD Agricultural Development plc,"April 4th, 2015",Other,Washed / Wet,...,10.00,10.00,8.75,90.58,0.12,0,Green,0,2075.0,Premium (Arabica)
1,Arabica,metad plc,Ethiopia,guji-hambela,300,60 kg,METAD Agricultural Development plc,"April 4th, 2015",Other,Washed / Wet,...,10.00,10.00,8.58,89.92,0.12,0,Green,1,2075.0,Premium (Arabica)
2,Arabica,grounds for health admin,Guatemala,No Especificado,5,1,Specialty Coffee Association,"May 31st, 2010",Bourbon,Washed / Wet,...,10.00,10.00,9.25,89.75,0.00,0,Green,0,1700.0,Alta (Arabica)
3,Arabica,yidnekachew dabessa,Ethiopia,oromia,320,60 kg,METAD Agricultural Development plc,"March 26th, 2015",Other,Natural / Dry,...,10.00,10.00,8.67,89.00,0.11,0,Green,2,2000.0,Premium (Arabica)
4,Arabica,metad plc,Ethiopia,guji-hambela,300,60 kg,METAD Agricultural Development plc,"April 4th, 2015",Other,Washed / Wet,...,10.00,10.00,8.58,88.83,0.12,0,Green,2,2075.0,Premium (Arabica)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334,Robusta,luis robles,Ecuador,"san juan, playas",1,2 kg,Specialty Coffee Association,"January 19th, 2016",No Especificado,No Especificado,...,10.00,7.75,7.83,78.75,0.00,0,Blue-Green,1,40.0,Baja (Robusta)
1335,Robusta,luis robles,Ecuador,"san juan, playas",1,2 kg,Specialty Coffee Association,"January 19th, 2016",No Especificado,No Especificado,...,10.00,8.42,8.58,78.08,0.00,0,Blue-Green,0,40.0,Baja (Robusta)
1336,Robusta,james moore,United States,"kwanza norte province, angola",1,1 kg,Specialty Coffee Association,"December 23rd, 2014",Arusha,Natural / Dry,...,9.33,7.42,7.17,77.17,0.00,0,Green,6,795.0,Alta (Robusta)
1337,Robusta,cafe politico,India,No Especificado,1,5 lbs,Specialty Coffee Association,"August 25th, 2014",Other,Natural / Dry,...,9.33,7.08,6.92,75.08,0.10,20,Green,1,1000.0,Alta (Robusta)
1338,Robusta,cafe politico,Vietnam,No Especificado,1,5 lbs,Specialty Coffee Association,"August 25th, 2014",No Especificado,Natural / Dry,...,9.33,6.67,7.92,73.75,0.12,63,No Especificado,9,1095.0,Alta (Robusta)

In [ ]:
print(df_merged_limpio.isnull().sum().sort_values(ascending=False).head(50))

Species                 0
Owner                   0
Country.of.Origin       0
Region                  0
Number.of.Bags          0
Bag.Weight              0
In.Country.Partner      0
Grading.Date            0
Variety                 0
Processing.Method       0
Aroma                   0
Flavor                  0
Aftertaste              0
Acidity                 0
Body                    0
Balance                 0
Uniformity              0
Clean.Cup               0
Sweetness               0
Cupper.Points           0
Total.Cup.Points        0
Moisture                0
Category.One.Defects    0
Color                   0
Category.Two.Defects    0
altitude_mean_meters    0
categoria_altitud       0
dtype: int64

# 7. Exportación del DataFrame limpio

In [18]:
df_merged_limpio.to_csv("../data/processed/coffee_data_cleaned_final.csv", index=False)